spring:
  application:
    name: product-service

  cloud:
    config:
      enabled: true

    openfeign:
      micrometer:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db
    username: root
    password: mysql@121212
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

  level:
    root: INFO
    com.product: DEBUG